// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreapp_demo.Context;

namespace coreapp_demo.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20200521092331_coreapp_demo.Models.Employee")]
    partial class coreapp_demoModelsEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("coreapp_demo.Models.Employee", b =>
                {
                    b.Property<long>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("department")
                        .HasColumnName("Department")
                        .HasMaxLength(100);

                    b.Property<string>("designation")
                        .HasColumnName("Designation")
                        .HasMaxLength(200);

                    b.Property<string>("firstName")
                        .HasColumnName("FirstName")
                        .HasMaxLength(30);

                    b.Property<string>("gender")
                        .HasColumnName("Gender")
                        .HasMaxLength(10);

                    b.Property<string>("lastName")
                        .HasColumnName("LastName")
                        .HasMaxLength(30);

                    b.HasKey("employeeId");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
